export const pictocodeToString: { [key: number]: string } = {
  1: 'Céu limpo',
  2: 'Poucas nuvens',
  3: 'Parcialmente nublado',
  4: 'Nublado',
  5: 'Nublado com chuvisco',
  6: 'Nublado com chuva fraca',
  7: 'Nublado com chuva',
  8: 'Nublado com chuva forte',
  9: 'Nublado com neve fraca',
  10: 'Nublado com neve',
  11: 'Nublado com neve forte',
  12: 'Nublado com chuva congelante',
  13: 'Nublado com granizo',
  14: 'Nublado com trovoada',
  15: 'Nevoeiro',
  16: 'Nevoeiro congelante',
  17: 'Céu limpo com trovoada',
  18: 'Poucas nuvens com trovoada',
  19: 'Parcialmente nublado com trovoada',
  20: 'Nublado com trovoada',
  21: 'Nublado com chuva fraca e trovoada',
  22: 'Nublado com chuva e trovoada',
  23: 'Nublado com chuva forte e trovoada',
  24: 'Nublado com neve fraca e trovoada',
  25: 'Nublado com neve e trovoada',
  26: 'Nublado com neve forte e trovoada',
  27: 'Nublado com chuva congelante e trovoada',
  28: 'Nublado com granizo e trovoada',
  29: 'Céu limpo com chuvisco',
  30: 'Poucas nuvens com chuvisco',
  31: 'Parcialmente nublado com chuvisco',
  32: 'Céu limpo com chuva fraca',
  33: 'Poucas nuvens com chuva fraca',
  34: 'Parcialmente nublado com chuva fraca',
  35: 'Céu limpo com chuva',
  36: 'Poucas nuvens com chuva',
  37: 'Parcialmente nublado com chuva',
  38: 'Céu limpo com chuva forte',
  39: 'Poucas nuvens com chuva forte',
  40: 'Parcialmente nublado com chuva forte',
  41: 'Céu limpo com neve fraca',
  42: 'Poucas nuvens com neve fraca',
  43: 'Parcialmente nublado com neve fraca',
  44: 'Céu limpo com neve',
  45: 'Poucas nuvens com neve',
  46: 'Parcialmente nublado com neve',
  47: 'Céu limpo com neve forte',
  48: 'Poucas nuvens com neve forte',
  49: 'Parcialmente nublado com neve forte',
  50: 'Céu limpo com chuva congelante',
  51: 'Poucas nuvens com chuva congelante',
  52: 'Parcialmente nublado com chuva congelante',
  53: 'Céu limpo com granizo',
  54: 'Poucas nuvens com granizo',
  55: 'Parcialmente nublado com granizo',
  56: 'Céu limpo com tempestade de areia/poeira',
  57: 'Poucas nuvens com tempestade de areia/poeira',
  58: 'Parcialmente nublado com tempestade de areia/poeira',
  59: 'Nublado com tempestade de areia/poeira',
  60: 'Céu limpo com tornado',
  61: 'Poucas nuvens com tornado',
  62: 'Parcialmente nublado com tornado',
  63: 'Nublado com tornado',
};
